@Library('Tawuniya-lib@main') _

pipeline {
  agent none

  parameters {
    string(name: 'EPIC', defaultValue: '', description: 'EPIC Number')
  }

  environment {
    BRANCH_NAME = 'QC'
  }

  stages {
    stage('Build + Scan') {
      steps {
        script {
          reactBuildScan(
            epic: params.EPIC,
            branch: env.BRANCH_NAME,
            lob: 'DXP',
            buildAgent: 'AS-L1',
            secretScanningAgent: 'built-in',
            sonarAgent: 'SonarQube',

            bbs: [
              credentialsId: 'Admin_Bitbucket',
              id: '75b95ed8-28cb-489d-b2fd-a56ac6b6f2ae',
              projectName: 'DXP',
              repositoryName: 'DH-Sales-V3',
              serverId: '2492752c-5622-4c29-9972-c1c0f572b1f6'
            ],

            app: [
              packageFile: 'package.json'
            ],

            node: [
              resetCmd: 'nx reset',
              installCmd: 'npm install --legacy-peer-deps',
              buildCmd: 'npx nx build mbi-claims-nr --configuration=development'
            ],
            
            artifacts: [
              path: 'dist/apps/mbi-claims-nr/**'
            ],

            sonar: [
              server: 'SonarQube',
              projectKey: 'MBI-CLAIMS-NR',
              projectName: 'MBI-CLAIMS-NR',
              sources: 'apps/mbi-claims-nr/src',
              exclusions: '**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/*.js,**/*.map'
            ]
          )
        }
      }
    }
  }
}